// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyjjohiyjitexuicdipo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5ampvaGl5aml0ZXh1aWNkaXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3OTQ0ODksImV4cCI6MjA1OTM3MDQ4OX0.ZqvH3JsvoIsGyZHcUW88jSP7LgseAGnmHQ8xKRrFAfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);